version: '3.8'

services:
  frontend:
    build:
      context: ./web-frontend
      dockerfile: Dockerfile
      args:
        - npm install
        - npm run build
    ports:
      - "80:80"
    volumes:
      - ./web-frontend/src:/usr/share/nginx/html
      - ./web-frontend/dist:/usr/share/nginx/html/dist
      - ./web-frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NODE_ENV=production
  frontend-test:
    build:
      context: ./web-frontend
      dockerfile: Dockerfile.test
    volumes:
      - ./web-frontend/src:/app/src
    environment:
      - NODE_ENV=test